### ISSUE TITLE
missing license

### ISSUE THREAD

**Issue by yumetodo** [h0tcat/easySetupMingw#3]
git cloneする権利がないことに気がついたので報告します

**Comment by h0tcat** [comment]
もしかして、git cloneするときにsshの方で行っていますか?
たとえば、git clone git@github.com:h0tcat/easySetupgcc.git

念のためgit clone する際に https:// の方で試してみてください!

git clone https://github.com/h0tcat/easySetupgcc

**Comment by yumetodo** [comment]
いえ、そうではなくライセンスがないコードはall rights reservedになります。ただしgithubの規約上forkだけはできます。git cloneは著作権侵害になってしまうのです。おそらく意図していない状態だと思うのでissueを立てました。

**Comment by h0tcat** [comment]
LICENSEを追加してみました。

まだ問題がある場合は報告いただきたいです。

**Comment by yumetodo** [comment]
ありがとうございます
