### ISSUE TITLE
このrepoについて調査したqiita記事の紹介

### ISSUE THREAD

**Issue by yumetodo** [h0tcat/easySetupMingw#4]
友人とこのrepoを大真面目にあーでもないこーでもないと深夜テンションで検討していたときに上がった問題点を友人がQiitaに記事にしたので紹介しておきます。
GitHubに上がってたeasySetupMingwというプロジェクトの発想が面白かった。でもWindowsは優しくなかった - Qiita
https://qiita.com/AinoMegumi/items/54e72c3663f6ecf5385d

**Comment by h0tcat** [comment]
Qiitaページ、拝見しました。

それにしてもWindowsって思ったより、複雑ですねぇ...
もっとスキルを上げて頑張ります!
